// src/messages.js — user-facing message catalog (en / ja)
//
// All console / generated-file strings from the loop engine (sleep, wake,
// review, weekly, monthly) live here so the CLI can speak the user's language.
//
// - Language is selected via config.json `language` ("en" by default).
// - Variables use the {{name}} form: t('sleep_forgetting_summary', { count: 3, days: 90 }).
// - Unknown keys fall back to the English catalog, then to the key itself,
//   so a missing translation never crashes a loop.
//
// Note on the ja catalog: brand-voice lines that have always been English
// ("Good night. Your brain is now dreaming...") intentionally stay English in
// ja as well. This keeps the product voice consistent and preserves the exact
// output existing Japanese installs see today.
import { loadConfig } from './util.js';

const en = {
  // ---- common -------------------------------------------------------------
  common_brain_not_found: 'Brain not found. Run `cerebralos init` first.',
  common_dry_run_suffix: ' (dry-run)',

  // ---- sleep (nightly loop) -----------------------------------------------
  sleep_start: 'Good night. Your brain is now dreaming...',
  sleep_dry_run_would_archive: '  [dry-run] would archive: {{file}}',
  sleep_forgetting_summary: 'Active Forgetting: {{count}} memories → archive (threshold: {{days}}d)',
  sleep_intelligence_running: 'Running intelligence layer ({{command}} -p, {{count}} files)...',
  sleep_intelligence_no_dream: 'Intelligence layer finished but no dream was written. Falling back.',
  sleep_intelligence_failed: 'Intelligence layer failed ({{error}}). Falling back.',
  sleep_dry_run_would_run_intelligence: '  [dry-run] would run {{command}} -p with {{count}} files (skill: {{skill}})',
  sleep_dry_run_intelligence_skipped: '  [dry-run] intelligence layer skipped (enabled={{enabled}}, skill={{skill}}, files={{count}})',
  sleep_dry_run_fallback_preview: '  [dry-run] fallback dream preview:',
  sleep_latest_dream_updated: 'dreams/latest.md updated.',
  sleep_complete: 'Sleep Job complete. A new Morning Insight is ready.',
  sleep_complete_dry_run: 'Sleep Job complete (dry-run, nothing written)',
  sleep_dream_title: 'Dream Log — {{date}}',
  sleep_dream_insight_header: 'Morning Insight',
  sleep_dream_quiet: 'The brain rested quietly tonight. Space was created.\nNo new activity was recorded.',
  sleep_dream_activity_header: "Yesterday's activity ({{count}} files, intelligence layer off — index only):",
  sleep_dream_footer: '*Generated by the Sleep Job (fallback layer) at {{time}}.*',

  // ---- wake (morning insight) ----------------------------------------------
  wake_insight_header: '☀ Morning Insight ({{date}})',
  wake_queue_header: '📥 Review queue: {{count}} pending',
  wake_queue_more: '  ... {{count}} more',
  wake_queue_hint: '→ cerebralos review to triage / approve <id> to promote',
  wake_deadline_header: '⏰ Deadline risks (portfolio/PORTFOLIO.md)',
  wake_deadline_overdue: '{{days}}d overdue',
  wake_deadline_today: 'today',
  wake_deadline_tomorrow: 'tomorrow',

  // ---- review (queue triage / swipe UI) -------------------------------------
  review_queue_empty: 'Review queue is empty. ({{path}})',
  review_list_header: 'Review queue — {{count}} pending',
  review_list_hint: '→ cerebralos approve <number|id> / reject <number|id> [reason] / approve --all',
  review_swipe_header: 'Review queue — {{count}} cards',
  review_swipe_tip: 'When unsure, swipe →. A bad promotion expires by itself after 90 days without references.',
  review_card_guide: '   ← reject        ↓ skip        approve →      (v:body q:quit)',
  review_no_title: '(no title)',
  review_no_body: '(no body)',
  review_quit_remaining: 'Quit. {{count}} cards left for next time.',
  review_reject_reason_prompt: '  Rejection reason (Enter for none): ',
  review_skip_done: '  ↓ skipped: {{title}}',
  review_summary_done: 'Review complete ☀',
  review_summary_counts: 'approved {{approved}} / rejected {{rejected}} / skipped {{skipped}}',
  review_not_found: 'Not found: {{id}}',
  review_already_done: '{{id}} is already {{status}}.',
  review_approve_usage: 'Usage: cerebralos approve <number|RQ-id> | --all',
  review_approve_missing_fields: '{{id}}: cannot promote — target / body is missing',
  review_approve_invalid_target: '{{id}}: target must be under knowledge/ (got: {{target}})',
  review_approve_target_exists: 'Already exists: {{target}}',
  review_approve_done: '  💚 Approved → {{target}} (committed to the knowledge repo)',
  review_approve_commit_failed: '  Write succeeded, but git commit failed: {{error}}',
  review_approve_recorded: '  💚 Marked {{id}} as approved (type: {{type}} is record-only)',
  review_reject_done: '  👋 Rejected: {{id}}',
  review_queue_file_note: 'Written by the nightly/weekly/monthly loops. Triage with `cerebralos review` → `approve/reject`.',

  // ---- weekly (inventory loop) ----------------------------------------------
  weekly_start: 'Weekly inventory...',
  weekly_dry_run_would_archive_session: '  [dry-run] would archive session: {{file}}',
  weekly_finding_sessions: 'peripheral/sessions: moved {{count}} files to archive/sessions (older than {{days}}d)',
  weekly_finding_expired_box: 'Expired deletion box: {{path}} (deadline {{date}}) → needs a delete decision',
  weekly_finding_links_review: 'Link needs re-check: {{file}} (review_after {{date}} passed) — confirm the location is still correct',
  weekly_no_findings: 'Weekly inventory: nothing to report',
  weekly_queue_title: 'Weekly inventory {{date}} ({{count}} findings)',
  weekly_queued: 'Weekly inventory: queued {{count}} findings for review',
  weekly_dry_run_would_queue: '  [dry-run] would queue {{count}} findings',

  // ---- monthly (storage hygiene loop) ----------------------------------------
  monthly_start: 'Monthly storage hygiene scan...',
  monthly_root_not_found: 'Scan root not found: {{path}}',
  monthly_category_summary: '{{label}}: total {{gb}} GB ({{count}} locations)',
  monthly_total: 'Total: {{gb}} GB (threshold {{threshold}} GB)',
  monthly_below_threshold: 'Monthly hygiene: below threshold, no report needed',
  monthly_queue_title: 'Monthly storage hygiene {{date}} — {{gb}} GB of regenerable data',
  monthly_queue_advice:
    'Suggested actions:\n' +
    '- node_modules: delete for dormant projects (regenerable via npm install)\n' +
    '- .stversions: check size and delete (see docs/operations.md)\n' +
    '- .git: compact with git gc',
  monthly_queued: 'Monthly hygiene: queued the report for review',
  monthly_dry_run_would_queue: '  [dry-run] would queue hygiene report',

  // ---- write (peripheral write command) --------------------------------------
  write_no_content: 'No content provided. Use --body or pipe content via stdin.',
  write_saved: 'Memory saved: {{path}}',

  // ---- mcp (write_memory / list_dreams tools) --------------------------------
  mcp_write_done: 'Memory saved: {{path}}',
  mcp_no_dreams: 'No dreams found yet.',
};

const ja = {
  // ---- common -------------------------------------------------------------
  common_brain_not_found: 'Brain not found. Run `cerebralos init` first.',
  common_dry_run_suffix: ' (dry-run)',

  // ---- sleep (nightly loop) -----------------------------------------------
  sleep_start: 'Good night. Your brain is now dreaming...',
  sleep_dry_run_would_archive: '  [dry-run] would archive: {{file}}',
  sleep_forgetting_summary: 'Active Forgetting: {{count}} memories → archive (threshold: {{days}}d)',
  sleep_intelligence_running: 'Running intelligence layer ({{command}} -p, {{count}} files)...',
  sleep_intelligence_no_dream: 'Intelligence layer finished but no dream was written. Falling back.',
  sleep_intelligence_failed: 'Intelligence layer failed ({{error}}). Falling back.',
  sleep_dry_run_would_run_intelligence: '  [dry-run] would run {{command}} -p with {{count}} files (skill: {{skill}})',
  sleep_dry_run_intelligence_skipped: '  [dry-run] intelligence layer skipped (enabled={{enabled}}, skill={{skill}}, files={{count}})',
  sleep_dry_run_fallback_preview: '  [dry-run] fallback dream preview:',
  sleep_latest_dream_updated: 'dreams/latest.md updated.',
  sleep_complete: 'Sleep Job complete. A new Morning Insight is ready.',
  sleep_complete_dry_run: 'Sleep Job complete (dry-run, nothing written)',
  sleep_dream_title: 'Dream Log — {{date}}',
  sleep_dream_insight_header: 'Morning Insight',
  sleep_dream_quiet: 'The brain rested quietly tonight. Space was created.\nNo new activity was recorded.',
  sleep_dream_activity_header: '昨日の活動（{{count}}件、知能層オフのため一覧のみ）:',
  sleep_dream_footer: '*Generated by the Sleep Job (fallback layer) at {{time}}.*',

  // ---- wake (morning insight) ----------------------------------------------
  wake_insight_header: '☀ Morning Insight ({{date}})',
  wake_queue_header: '📥 Review queue: {{count}} pending',
  wake_queue_more: '  ... 他 {{count}} 件',
  wake_queue_hint: '→ cerebralos review で一覧 / approve <id> で昇格',
  wake_deadline_header: '⏰ 締切リスク（portfolio/PORTFOLIO.md）',
  wake_deadline_overdue: '期限超過 {{days}}日',
  wake_deadline_today: '今日',
  wake_deadline_tomorrow: '明日',

  // ---- review (queue triage / swipe UI) -------------------------------------
  review_queue_empty: 'Review queue is empty. ({{path}})',
  review_list_header: 'Review queue — {{count}} pending',
  review_list_hint: '→ cerebralos approve <番号|id> / reject <番号|id> [理由] / approve --all',
  review_swipe_header: 'Review queue — {{count}} 件',
  review_swipe_tip: '迷ったら → でOK。ハズレ昇格は90日無参照で自然消滅します。',
  review_card_guide: '   ← 却下        ↓ スキップ        承認 →      (v:本文 q:終了)',
  review_no_title: '(no title)',
  review_no_body: '(本文なし)',
  review_quit_remaining: '終了。残り {{count}} 件は次回に。',
  review_reject_reason_prompt: '  却下理由（Enterでなし）: ',
  review_skip_done: '  ↓ スキップ: {{title}}',
  review_summary_done: 'レビュー完了 ☀',
  review_summary_counts: '承認 {{approved}} / 却下 {{rejected}} / スキップ {{skipped}}',
  review_not_found: 'Not found: {{id}}',
  review_already_done: '{{id}} is already {{status}}.',
  review_approve_usage: 'Usage: cerebralos approve <番号|RQ-id> | --all',
  review_approve_missing_fields: '{{id}}: target / body が無いため昇格できません',
  review_approve_invalid_target: '{{id}}: target は knowledge/ 配下のみ許可（got: {{target}}）',
  review_approve_target_exists: '既に存在します: {{target}}',
  review_approve_done: '  💚 承認 → {{target}}（knowledge リポジトリにコミット済み）',
  review_approve_commit_failed: '  書き込み成功、git commit は失敗: {{error}}',
  review_approve_recorded: '  💚 {{id}} を approved にしました（type: {{type}} は記録のみ）',
  review_reject_done: '  👋 却下: {{id}}',
  review_queue_file_note: 'Nightly/Weekly/Monthly ループが書き、`cerebralos review` → `approve/reject` で捌く。',

  // ---- weekly (inventory loop) ----------------------------------------------
  weekly_start: 'Weekly inventory...',
  weekly_dry_run_would_archive_session: '  [dry-run] would archive session: {{file}}',
  weekly_finding_sessions: 'peripheral/sessions: {{count}} 件を archive/sessions へ移動（{{days}}日超）',
  weekly_finding_expired_box: '期限超過の削除箱: {{path}}（期限 {{date}}）→ 削除判断が必要',
  weekly_finding_links_review: 'links 要再確認: {{file}}（review_after {{date}} 超過）— 所在が今も正しいか確認',
  weekly_no_findings: 'Weekly inventory: 異常なし',
  weekly_queue_title: '週次棚卸 {{date}}（{{count}}件）',
  weekly_queued: 'Weekly inventory: {{count}} 件を review-queue に登録',
  weekly_dry_run_would_queue: '  [dry-run] would queue {{count}} findings',

  // ---- monthly (storage hygiene loop) ----------------------------------------
  monthly_start: 'Monthly storage hygiene scan...',
  monthly_root_not_found: 'スキャン対象が見つかりません: {{path}}',
  monthly_category_summary: '{{label}}: 合計 {{gb}} GB（{{count}} 箇所）',
  monthly_total: '総計: {{gb}} GB（閾値 {{threshold}} GB）',
  monthly_below_threshold: 'Monthly hygiene: 閾値以下、レポート不要',
  monthly_queue_title: '月次ストレージ衛生 {{date}} — 再生成可能データ {{gb}} GB',
  monthly_queue_advice:
    '対応の目安:\n' +
    '- node_modules: 休眠プロジェクトは削除（npm install で再生成可）\n' +
    '- .stversions: docs/operations.md の手順でサイズ確認・削除\n' +
    '- .git: git gc で圧縮',
  monthly_queued: 'Monthly hygiene: review-queue にレポートを登録',
  monthly_dry_run_would_queue: '  [dry-run] would queue hygiene report',

  // ---- write (peripheral write command) --------------------------------------
  write_no_content: 'コンテンツが指定されていません。--body またはstdin経由でパイプしてください。',
  write_saved: 'メモリを保存しました: {{path}}',

  // ---- mcp (write_memory / list_dreams tools) --------------------------------
  mcp_write_done: 'メモリを保存しました: {{path}}',
  mcp_no_dreams: '夢はまだありません。',
};

export const MESSAGES = { en, ja };

let languageOverride = null;

// Force a language at runtime (used by tests). Pass null to go back to config.
export function setLanguage(lang) {
  languageOverride = lang && Object.hasOwn(MESSAGES, lang) ? lang : null;
}

function currentLanguage() {
  if (languageOverride) return languageOverride;
  const lang = loadConfig().language;
  return typeof lang === 'string' && Object.hasOwn(MESSAGES, lang) ? lang : 'en';
}

// Translate a message key, substituting {{name}} placeholders from vars.
// Falls back: selected language → English → the key itself.
export function t(key, vars = {}) {
  const dict = MESSAGES[currentLanguage()];
  let msg = dict[key] ?? en[key] ?? key;
  for (const [name, value] of Object.entries(vars)) {
    msg = msg.replaceAll(`{{${name}}}`, String(value));
  }
  return msg;
}
